awsRegion: us-east-1

rbac:
  create: true
  serviceAccount:
    # This value should match local.k8s_service_account_name in locals.tf
    name: cluster-autoscaler-aws-cluster-autoscaler-chart
    annotations:
      # This value should match the ARN of the role created by module.iam_assumable_role_admin in irsa.tf
      eks.amazonaws.com/role-arn: "arn:aws:iam::201973737062:role/cluster-autoscaler"

autoDiscovery:
  clusterName: express-eks-98dUl29m
  enabled: true
