apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: express-app
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express-app
  targetCPUUtilizationPercentage: 20 # artificially low for demonstration
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60 # artificially low for demonstration

