apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: express-app
  name: express-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-app
  strategy: {}
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - image: michaeldbianchi/express-app
        name: express-app
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 500m

---

apiVersion: v1
kind: Service
metadata:
  name: express-app
spec:
  selector:
    app: express-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: express-app
spec:
  maxReplicas: 20
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express-app
  targetCPUUtilizationPercentage: 20 # artificially low for demonstration
