name: deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: michaeldbianchi/express-app

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: Dockerfile
  build-and-push:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Build and Upload Image
        env:
          DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_REGISTRY_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          timestamp=$(date +"%Y%m%d%H%M")
          docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_ACCESS_TOKEN
          docker pull $IMAGE_NAME || echo "Failed to pull $IMAGE_NAME image - Building from scratch"
          docker build --cache-from $IMAGE_NAME -t $IMAGE_NAME:${GITHUB_SHA::8} -t $IMAGE_NAME:$timestamp -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME 
            
  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      # - name: Install dependencies
      #   run: ./bin/install-deps.sh
      - name: Validate dependencies
        run: ./bin/check-deps.sh
